version: "3.3"

services:
  pandora:
    image: ghcr.io/jiz4oh/efb
    container_name: efb
    volumes:
      - ./ehforwarderbot:/data
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
